POST http://localhost:8000/posts
Content-Type: application/json

{
    "title": "Nest.js News",
    "postType": "post",
    "slug": "new-with-nest-js-new",
    "status": "draft",
    "content": "Nest.js is a modern framework for building efficient, scalable server-side applications with Node.js.",
    "schema": "{}",
    "featuredImageUrl": "http://localhost.com/images/image1.jpg",
    "publishOn": "2024-03-16T07:46:32+0000",
    "tags": [
        "nest.js",
        "typescript"
    ],
    "metaOptions": {
        "metaValue": "{\"name\":\"Mohamed Almatry\"}"
    }
}